//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPlantillaBaseBO.ServicioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="softplantilla.services", ConfigurationName="ServicioWS.PersonaWS")]
    public interface PersonaWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="softplantilla.services/PersonaWS/obtenerPersonaPorIdRequest", ReplyAction="softplantilla.services/PersonaWS/obtenerPersonaPorIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPlantillaBaseBO.ServicioWS.obtenerPersonaPorIdResponse obtenerPersonaPorId(SoftPlantillaBaseBO.ServicioWS.obtenerPersonaPorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="softplantilla.services/PersonaWS/obtenerPersonaPorIdRequest", ReplyAction="softplantilla.services/PersonaWS/obtenerPersonaPorIdResponse")]
        System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.obtenerPersonaPorIdResponse> obtenerPersonaPorIdAsync(SoftPlantillaBaseBO.ServicioWS.obtenerPersonaPorIdRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="softplantilla.services/PersonaWS/listarPersonasTodasRequest", ReplyAction="softplantilla.services/PersonaWS/listarPersonasTodasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPlantillaBaseBO.ServicioWS.listarPersonasTodasResponse listarPersonasTodas(SoftPlantillaBaseBO.ServicioWS.listarPersonasTodasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="softplantilla.services/PersonaWS/listarPersonasTodasRequest", ReplyAction="softplantilla.services/PersonaWS/listarPersonasTodasResponse")]
        System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.listarPersonasTodasResponse> listarPersonasTodasAsync(SoftPlantillaBaseBO.ServicioWS.listarPersonasTodasRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="softplantilla.services/PersonaWS/eliminarPersonaRequest", ReplyAction="softplantilla.services/PersonaWS/eliminarPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPlantillaBaseBO.ServicioWS.eliminarPersonaResponse eliminarPersona(SoftPlantillaBaseBO.ServicioWS.eliminarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="softplantilla.services/PersonaWS/eliminarPersonaRequest", ReplyAction="softplantilla.services/PersonaWS/eliminarPersonaResponse")]
        System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.eliminarPersonaResponse> eliminarPersonaAsync(SoftPlantillaBaseBO.ServicioWS.eliminarPersonaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="softplantilla.services/PersonaWS/modificarPersonaRequest", ReplyAction="softplantilla.services/PersonaWS/modificarPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPlantillaBaseBO.ServicioWS.modificarPersonaResponse modificarPersona(SoftPlantillaBaseBO.ServicioWS.modificarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="softplantilla.services/PersonaWS/modificarPersonaRequest", ReplyAction="softplantilla.services/PersonaWS/modificarPersonaResponse")]
        System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.modificarPersonaResponse> modificarPersonaAsync(SoftPlantillaBaseBO.ServicioWS.modificarPersonaRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="softplantilla.services/PersonaWS/insertarPersonaRequest", ReplyAction="softplantilla.services/PersonaWS/insertarPersonaResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPlantillaBaseBO.ServicioWS.insertarPersonaResponse insertarPersona(SoftPlantillaBaseBO.ServicioWS.insertarPersonaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="softplantilla.services/PersonaWS/insertarPersonaRequest", ReplyAction="softplantilla.services/PersonaWS/insertarPersonaResponse")]
        System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.insertarPersonaResponse> insertarPersonaAsync(SoftPlantillaBaseBO.ServicioWS.insertarPersonaRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="softplantilla.services")]
    public partial class persona : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private bool activoFieldSpecified;
        
        private double alturaField;
        
        private bool alturaFieldSpecified;
        
        private string apellidoField;
        
        private System.DateTime fechaNacimientoField;
        
        private bool fechaNacimientoFieldSpecified;
        
        private int idPersonaField;
        
        private bool idPersonaFieldSpecified;
        
        private string nombreField;
        
        private tipo tipoField;
        
        private bool tipoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activoSpecified {
            get {
                return this.activoFieldSpecified;
            }
            set {
                this.activoFieldSpecified = value;
                this.RaisePropertyChanged("activoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public double altura {
            get {
                return this.alturaField;
            }
            set {
                this.alturaField = value;
                this.RaisePropertyChanged("altura");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool alturaSpecified {
            get {
                return this.alturaFieldSpecified;
            }
            set {
                this.alturaFieldSpecified = value;
                this.RaisePropertyChanged("alturaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string apellido {
            get {
                return this.apellidoField;
            }
            set {
                this.apellidoField = value;
                this.RaisePropertyChanged("apellido");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime fechaNacimiento {
            get {
                return this.fechaNacimientoField;
            }
            set {
                this.fechaNacimientoField = value;
                this.RaisePropertyChanged("fechaNacimiento");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaNacimientoSpecified {
            get {
                return this.fechaNacimientoFieldSpecified;
            }
            set {
                this.fechaNacimientoFieldSpecified = value;
                this.RaisePropertyChanged("fechaNacimientoSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int idPersona {
            get {
                return this.idPersonaField;
            }
            set {
                this.idPersonaField = value;
                this.RaisePropertyChanged("idPersona");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idPersonaSpecified {
            get {
                return this.idPersonaFieldSpecified;
            }
            set {
                this.idPersonaFieldSpecified = value;
                this.RaisePropertyChanged("idPersonaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public tipo tipo {
            get {
                return this.tipoField;
            }
            set {
                this.tipoField = value;
                this.RaisePropertyChanged("tipo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tipoSpecified {
            get {
                return this.tipoFieldSpecified;
            }
            set {
                this.tipoFieldSpecified = value;
                this.RaisePropertyChanged("tipoSpecified");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9032.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="softplantilla.services")]
    public enum tipo {
        
        /// <remarks/>
        Estudiante,
        
        /// <remarks/>
        Profesor,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPersonaPorId", WrapperNamespace="softplantilla.services", IsWrapped=true)]
    public partial class obtenerPersonaPorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public obtenerPersonaPorIdRequest() {
        }
        
        public obtenerPersonaPorIdRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="obtenerPersonaPorIdResponse", WrapperNamespace="softplantilla.services", IsWrapped=true)]
    public partial class obtenerPersonaPorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPlantillaBaseBO.ServicioWS.persona @return;
        
        public obtenerPersonaPorIdResponse() {
        }
        
        public obtenerPersonaPorIdResponse(SoftPlantillaBaseBO.ServicioWS.persona @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPersonasTodas", WrapperNamespace="softplantilla.services", IsWrapped=true)]
    public partial class listarPersonasTodasRequest {
        
        public listarPersonasTodasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarPersonasTodasResponse", WrapperNamespace="softplantilla.services", IsWrapped=true)]
    public partial class listarPersonasTodasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPlantillaBaseBO.ServicioWS.persona[] @return;
        
        public listarPersonasTodasResponse() {
        }
        
        public listarPersonasTodasResponse(SoftPlantillaBaseBO.ServicioWS.persona[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPersona", WrapperNamespace="softplantilla.services", IsWrapped=true)]
    public partial class eliminarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        public eliminarPersonaRequest() {
        }
        
        public eliminarPersonaRequest(int arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="eliminarPersonaResponse", WrapperNamespace="softplantilla.services", IsWrapped=true)]
    public partial class eliminarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public eliminarPersonaResponse() {
        }
        
        public eliminarPersonaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPersona", WrapperNamespace="softplantilla.services", IsWrapped=true)]
    public partial class modificarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPlantillaBaseBO.ServicioWS.tipo arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg5;
        
        public modificarPersonaRequest() {
        }
        
        public modificarPersonaRequest(int arg0, string arg1, string arg2, double arg3, SoftPlantillaBaseBO.ServicioWS.tipo arg4, System.DateTime arg5) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="modificarPersonaResponse", WrapperNamespace="softplantilla.services", IsWrapped=true)]
    public partial class modificarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public modificarPersonaResponse() {
        }
        
        public modificarPersonaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPersona", WrapperNamespace="softplantilla.services", IsWrapped=true)]
    public partial class insertarPersonaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPlantillaBaseBO.ServicioWS.tipo arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg4;
        
        public insertarPersonaRequest() {
        }
        
        public insertarPersonaRequest(string arg0, string arg1, double arg2, SoftPlantillaBaseBO.ServicioWS.tipo arg3, System.DateTime arg4) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPersonaResponse", WrapperNamespace="softplantilla.services", IsWrapped=true)]
    public partial class insertarPersonaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPersonaResponse() {
        }
        
        public insertarPersonaResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PersonaWSChannel : SoftPlantillaBaseBO.ServicioWS.PersonaWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonaWSClient : System.ServiceModel.ClientBase<SoftPlantillaBaseBO.ServicioWS.PersonaWS>, SoftPlantillaBaseBO.ServicioWS.PersonaWS {
        
        public PersonaWSClient() {
        }
        
        public PersonaWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonaWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonaWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPlantillaBaseBO.ServicioWS.obtenerPersonaPorIdResponse SoftPlantillaBaseBO.ServicioWS.PersonaWS.obtenerPersonaPorId(SoftPlantillaBaseBO.ServicioWS.obtenerPersonaPorIdRequest request) {
            return base.Channel.obtenerPersonaPorId(request);
        }
        
        public SoftPlantillaBaseBO.ServicioWS.persona obtenerPersonaPorId(int arg0) {
            SoftPlantillaBaseBO.ServicioWS.obtenerPersonaPorIdRequest inValue = new SoftPlantillaBaseBO.ServicioWS.obtenerPersonaPorIdRequest();
            inValue.arg0 = arg0;
            SoftPlantillaBaseBO.ServicioWS.obtenerPersonaPorIdResponse retVal = ((SoftPlantillaBaseBO.ServicioWS.PersonaWS)(this)).obtenerPersonaPorId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.obtenerPersonaPorIdResponse> SoftPlantillaBaseBO.ServicioWS.PersonaWS.obtenerPersonaPorIdAsync(SoftPlantillaBaseBO.ServicioWS.obtenerPersonaPorIdRequest request) {
            return base.Channel.obtenerPersonaPorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.obtenerPersonaPorIdResponse> obtenerPersonaPorIdAsync(int arg0) {
            SoftPlantillaBaseBO.ServicioWS.obtenerPersonaPorIdRequest inValue = new SoftPlantillaBaseBO.ServicioWS.obtenerPersonaPorIdRequest();
            inValue.arg0 = arg0;
            return ((SoftPlantillaBaseBO.ServicioWS.PersonaWS)(this)).obtenerPersonaPorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPlantillaBaseBO.ServicioWS.listarPersonasTodasResponse SoftPlantillaBaseBO.ServicioWS.PersonaWS.listarPersonasTodas(SoftPlantillaBaseBO.ServicioWS.listarPersonasTodasRequest request) {
            return base.Channel.listarPersonasTodas(request);
        }
        
        public SoftPlantillaBaseBO.ServicioWS.persona[] listarPersonasTodas() {
            SoftPlantillaBaseBO.ServicioWS.listarPersonasTodasRequest inValue = new SoftPlantillaBaseBO.ServicioWS.listarPersonasTodasRequest();
            SoftPlantillaBaseBO.ServicioWS.listarPersonasTodasResponse retVal = ((SoftPlantillaBaseBO.ServicioWS.PersonaWS)(this)).listarPersonasTodas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.listarPersonasTodasResponse> SoftPlantillaBaseBO.ServicioWS.PersonaWS.listarPersonasTodasAsync(SoftPlantillaBaseBO.ServicioWS.listarPersonasTodasRequest request) {
            return base.Channel.listarPersonasTodasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.listarPersonasTodasResponse> listarPersonasTodasAsync() {
            SoftPlantillaBaseBO.ServicioWS.listarPersonasTodasRequest inValue = new SoftPlantillaBaseBO.ServicioWS.listarPersonasTodasRequest();
            return ((SoftPlantillaBaseBO.ServicioWS.PersonaWS)(this)).listarPersonasTodasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPlantillaBaseBO.ServicioWS.eliminarPersonaResponse SoftPlantillaBaseBO.ServicioWS.PersonaWS.eliminarPersona(SoftPlantillaBaseBO.ServicioWS.eliminarPersonaRequest request) {
            return base.Channel.eliminarPersona(request);
        }
        
        public int eliminarPersona(int arg0) {
            SoftPlantillaBaseBO.ServicioWS.eliminarPersonaRequest inValue = new SoftPlantillaBaseBO.ServicioWS.eliminarPersonaRequest();
            inValue.arg0 = arg0;
            SoftPlantillaBaseBO.ServicioWS.eliminarPersonaResponse retVal = ((SoftPlantillaBaseBO.ServicioWS.PersonaWS)(this)).eliminarPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.eliminarPersonaResponse> SoftPlantillaBaseBO.ServicioWS.PersonaWS.eliminarPersonaAsync(SoftPlantillaBaseBO.ServicioWS.eliminarPersonaRequest request) {
            return base.Channel.eliminarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.eliminarPersonaResponse> eliminarPersonaAsync(int arg0) {
            SoftPlantillaBaseBO.ServicioWS.eliminarPersonaRequest inValue = new SoftPlantillaBaseBO.ServicioWS.eliminarPersonaRequest();
            inValue.arg0 = arg0;
            return ((SoftPlantillaBaseBO.ServicioWS.PersonaWS)(this)).eliminarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPlantillaBaseBO.ServicioWS.modificarPersonaResponse SoftPlantillaBaseBO.ServicioWS.PersonaWS.modificarPersona(SoftPlantillaBaseBO.ServicioWS.modificarPersonaRequest request) {
            return base.Channel.modificarPersona(request);
        }
        
        public int modificarPersona(int arg0, string arg1, string arg2, double arg3, SoftPlantillaBaseBO.ServicioWS.tipo arg4, System.DateTime arg5) {
            SoftPlantillaBaseBO.ServicioWS.modificarPersonaRequest inValue = new SoftPlantillaBaseBO.ServicioWS.modificarPersonaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            SoftPlantillaBaseBO.ServicioWS.modificarPersonaResponse retVal = ((SoftPlantillaBaseBO.ServicioWS.PersonaWS)(this)).modificarPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.modificarPersonaResponse> SoftPlantillaBaseBO.ServicioWS.PersonaWS.modificarPersonaAsync(SoftPlantillaBaseBO.ServicioWS.modificarPersonaRequest request) {
            return base.Channel.modificarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.modificarPersonaResponse> modificarPersonaAsync(int arg0, string arg1, string arg2, double arg3, SoftPlantillaBaseBO.ServicioWS.tipo arg4, System.DateTime arg5) {
            SoftPlantillaBaseBO.ServicioWS.modificarPersonaRequest inValue = new SoftPlantillaBaseBO.ServicioWS.modificarPersonaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            return ((SoftPlantillaBaseBO.ServicioWS.PersonaWS)(this)).modificarPersonaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPlantillaBaseBO.ServicioWS.insertarPersonaResponse SoftPlantillaBaseBO.ServicioWS.PersonaWS.insertarPersona(SoftPlantillaBaseBO.ServicioWS.insertarPersonaRequest request) {
            return base.Channel.insertarPersona(request);
        }
        
        public int insertarPersona(string arg0, string arg1, double arg2, SoftPlantillaBaseBO.ServicioWS.tipo arg3, System.DateTime arg4) {
            SoftPlantillaBaseBO.ServicioWS.insertarPersonaRequest inValue = new SoftPlantillaBaseBO.ServicioWS.insertarPersonaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            SoftPlantillaBaseBO.ServicioWS.insertarPersonaResponse retVal = ((SoftPlantillaBaseBO.ServicioWS.PersonaWS)(this)).insertarPersona(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.insertarPersonaResponse> SoftPlantillaBaseBO.ServicioWS.PersonaWS.insertarPersonaAsync(SoftPlantillaBaseBO.ServicioWS.insertarPersonaRequest request) {
            return base.Channel.insertarPersonaAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.insertarPersonaResponse> insertarPersonaAsync(string arg0, string arg1, double arg2, SoftPlantillaBaseBO.ServicioWS.tipo arg3, System.DateTime arg4) {
            SoftPlantillaBaseBO.ServicioWS.insertarPersonaRequest inValue = new SoftPlantillaBaseBO.ServicioWS.insertarPersonaRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            return ((SoftPlantillaBaseBO.ServicioWS.PersonaWS)(this)).insertarPersonaAsync(inValue);
        }
    }
}
