//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SazonWareWA.ServicioWeb {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="services.sazonware.pucp.edu.pe", ConfigurationName="ServicioWeb.PlatoWS")]
    public interface PlatoWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="services.sazonware.pucp.edu.pe/PlatoWS/insertarPlatoRequest", ReplyAction="services.sazonware.pucp.edu.pe/PlatoWS/insertarPlatoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SazonWareWA.ServicioWeb.insertarPlatoResponse insertarPlato(SazonWareWA.ServicioWeb.insertarPlatoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="services.sazonware.pucp.edu.pe/PlatoWS/insertarPlatoRequest", ReplyAction="services.sazonware.pucp.edu.pe/PlatoWS/insertarPlatoResponse")]
        System.Threading.Tasks.Task<SazonWareWA.ServicioWeb.insertarPlatoResponse> insertarPlatoAsync(SazonWareWA.ServicioWeb.insertarPlatoRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.sazonware.pucp.edu.pe")]
    public partial class plato : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private categoria categoriaField;
        
        private bool categoriaFieldSpecified;
        
        private byte[] fotoField;
        
        private int idPlatoField;
        
        private ingrediente[] ingredientesField;
        
        private string nombreField;
        
        private double precioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public categoria categoria {
            get {
                return this.categoriaField;
            }
            set {
                this.categoriaField = value;
                this.RaisePropertyChanged("categoria");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool categoriaSpecified {
            get {
                return this.categoriaFieldSpecified;
            }
            set {
                this.categoriaFieldSpecified = value;
                this.RaisePropertyChanged("categoriaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] foto {
            get {
                return this.fotoField;
            }
            set {
                this.fotoField = value;
                this.RaisePropertyChanged("foto");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int idPlato {
            get {
                return this.idPlatoField;
            }
            set {
                this.idPlatoField = value;
                this.RaisePropertyChanged("idPlato");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ingredientes", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=4)]
        public ingrediente[] ingredientes {
            get {
                return this.ingredientesField;
            }
            set {
                this.ingredientesField = value;
                this.RaisePropertyChanged("ingredientes");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public double precio {
            get {
                return this.precioField;
            }
            set {
                this.precioField = value;
                this.RaisePropertyChanged("precio");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.sazonware.pucp.edu.pe")]
    public enum categoria {
        
        /// <remarks/>
        ENTRADA,
        
        /// <remarks/>
        FONDO,
        
        /// <remarks/>
        POSTRE,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="services.sazonware.pucp.edu.pe")]
    public partial class ingrediente : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activoField;
        
        private string descripcionField;
        
        private int idIngredienteField;
        
        private string nombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activo {
            get {
                return this.activoField;
            }
            set {
                this.activoField = value;
                this.RaisePropertyChanged("activo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string descripcion {
            get {
                return this.descripcionField;
            }
            set {
                this.descripcionField = value;
                this.RaisePropertyChanged("descripcion");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int idIngrediente {
            get {
                return this.idIngredienteField;
            }
            set {
                this.idIngredienteField = value;
                this.RaisePropertyChanged("idIngrediente");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPlato", WrapperNamespace="services.sazonware.pucp.edu.pe", IsWrapped=true)]
    public partial class insertarPlatoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.sazonware.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SazonWareWA.ServicioWeb.plato plato;
        
        public insertarPlatoRequest() {
        }
        
        public insertarPlatoRequest(SazonWareWA.ServicioWeb.plato plato) {
            this.plato = plato;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPlatoResponse", WrapperNamespace="services.sazonware.pucp.edu.pe", IsWrapped=true)]
    public partial class insertarPlatoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.sazonware.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPlatoResponse() {
        }
        
        public insertarPlatoResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PlatoWSChannel : SazonWareWA.ServicioWeb.PlatoWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PlatoWSClient : System.ServiceModel.ClientBase<SazonWareWA.ServicioWeb.PlatoWS>, SazonWareWA.ServicioWeb.PlatoWS {
        
        public PlatoWSClient() {
        }
        
        public PlatoWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PlatoWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatoWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PlatoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SazonWareWA.ServicioWeb.insertarPlatoResponse SazonWareWA.ServicioWeb.PlatoWS.insertarPlato(SazonWareWA.ServicioWeb.insertarPlatoRequest request) {
            return base.Channel.insertarPlato(request);
        }
        
        public int insertarPlato(SazonWareWA.ServicioWeb.plato plato) {
            SazonWareWA.ServicioWeb.insertarPlatoRequest inValue = new SazonWareWA.ServicioWeb.insertarPlatoRequest();
            inValue.plato = plato;
            SazonWareWA.ServicioWeb.insertarPlatoResponse retVal = ((SazonWareWA.ServicioWeb.PlatoWS)(this)).insertarPlato(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SazonWareWA.ServicioWeb.insertarPlatoResponse> SazonWareWA.ServicioWeb.PlatoWS.insertarPlatoAsync(SazonWareWA.ServicioWeb.insertarPlatoRequest request) {
            return base.Channel.insertarPlatoAsync(request);
        }
        
        public System.Threading.Tasks.Task<SazonWareWA.ServicioWeb.insertarPlatoResponse> insertarPlatoAsync(SazonWareWA.ServicioWeb.plato plato) {
            SazonWareWA.ServicioWeb.insertarPlatoRequest inValue = new SazonWareWA.ServicioWeb.insertarPlatoRequest();
            inValue.plato = plato;
            return ((SazonWareWA.ServicioWeb.PlatoWS)(this)).insertarPlatoAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="services.sazonware.pucp.edu.pe", ConfigurationName="ServicioWeb.IngredienteWS")]
    public interface IngredienteWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="services.sazonware.pucp.edu.pe/IngredienteWS/listarIngredientesTodosRequest", ReplyAction="services.sazonware.pucp.edu.pe/IngredienteWS/listarIngredientesTodosResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SazonWareWA.ServicioWeb.listarIngredientesTodosResponse listarIngredientesTodos(SazonWareWA.ServicioWeb.listarIngredientesTodosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="services.sazonware.pucp.edu.pe/IngredienteWS/listarIngredientesTodosRequest", ReplyAction="services.sazonware.pucp.edu.pe/IngredienteWS/listarIngredientesTodosResponse")]
        System.Threading.Tasks.Task<SazonWareWA.ServicioWeb.listarIngredientesTodosResponse> listarIngredientesTodosAsync(SazonWareWA.ServicioWeb.listarIngredientesTodosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngredientesTodos", WrapperNamespace="services.sazonware.pucp.edu.pe", IsWrapped=true)]
    public partial class listarIngredientesTodosRequest {
        
        public listarIngredientesTodosRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarIngredientesTodosResponse", WrapperNamespace="services.sazonware.pucp.edu.pe", IsWrapped=true)]
    public partial class listarIngredientesTodosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="services.sazonware.pucp.edu.pe", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SazonWareWA.ServicioWeb.ingrediente[] @return;
        
        public listarIngredientesTodosResponse() {
        }
        
        public listarIngredientesTodosResponse(SazonWareWA.ServicioWeb.ingrediente[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IngredienteWSChannel : SazonWareWA.ServicioWeb.IngredienteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IngredienteWSClient : System.ServiceModel.ClientBase<SazonWareWA.ServicioWeb.IngredienteWS>, SazonWareWA.ServicioWeb.IngredienteWS {
        
        public IngredienteWSClient() {
        }
        
        public IngredienteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public IngredienteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngredienteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public IngredienteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SazonWareWA.ServicioWeb.listarIngredientesTodosResponse SazonWareWA.ServicioWeb.IngredienteWS.listarIngredientesTodos(SazonWareWA.ServicioWeb.listarIngredientesTodosRequest request) {
            return base.Channel.listarIngredientesTodos(request);
        }
        
        public SazonWareWA.ServicioWeb.ingrediente[] listarIngredientesTodos() {
            SazonWareWA.ServicioWeb.listarIngredientesTodosRequest inValue = new SazonWareWA.ServicioWeb.listarIngredientesTodosRequest();
            SazonWareWA.ServicioWeb.listarIngredientesTodosResponse retVal = ((SazonWareWA.ServicioWeb.IngredienteWS)(this)).listarIngredientesTodos(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SazonWareWA.ServicioWeb.listarIngredientesTodosResponse> SazonWareWA.ServicioWeb.IngredienteWS.listarIngredientesTodosAsync(SazonWareWA.ServicioWeb.listarIngredientesTodosRequest request) {
            return base.Channel.listarIngredientesTodosAsync(request);
        }
        
        public System.Threading.Tasks.Task<SazonWareWA.ServicioWeb.listarIngredientesTodosResponse> listarIngredientesTodosAsync() {
            SazonWareWA.ServicioWeb.listarIngredientesTodosRequest inValue = new SazonWareWA.ServicioWeb.listarIngredientesTodosRequest();
            return ((SazonWareWA.ServicioWeb.IngredienteWS)(this)).listarIngredientesTodosAsync(inValue);
        }
    }
}
