//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SoftPlantillaBaseBO.ServicioWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="softplantilla.services", ConfigurationName="ServicioWS.UniversidadWS")]
    public interface UniversidadWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="softplantilla.services/UniversidadWS/listarUniversidadesTodasRequest", ReplyAction="softplantilla.services/UniversidadWS/listarUniversidadesTodasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPlantillaBaseBO.ServicioWS.listarUniversidadesTodasResponse listarUniversidadesTodas(SoftPlantillaBaseBO.ServicioWS.listarUniversidadesTodasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="softplantilla.services/UniversidadWS/listarUniversidadesTodasRequest", ReplyAction="softplantilla.services/UniversidadWS/listarUniversidadesTodasResponse")]
        System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.listarUniversidadesTodasResponse> listarUniversidadesTodasAsync(SoftPlantillaBaseBO.ServicioWS.listarUniversidadesTodasRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="softplantilla.services")]
    public partial class universidad : object, System.ComponentModel.INotifyPropertyChanged {
        
        private bool activaField;
        
        private bool activaFieldSpecified;
        
        private int idUniversidadField;
        
        private bool idUniversidadFieldSpecified;
        
        private string nombreField;
        
        private string siglasField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool activa {
            get {
                return this.activaField;
            }
            set {
                this.activaField = value;
                this.RaisePropertyChanged("activa");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool activaSpecified {
            get {
                return this.activaFieldSpecified;
            }
            set {
                this.activaFieldSpecified = value;
                this.RaisePropertyChanged("activaSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int idUniversidad {
            get {
                return this.idUniversidadField;
            }
            set {
                this.idUniversidadField = value;
                this.RaisePropertyChanged("idUniversidad");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUniversidadSpecified {
            get {
                return this.idUniversidadFieldSpecified;
            }
            set {
                this.idUniversidadFieldSpecified = value;
                this.RaisePropertyChanged("idUniversidadSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                this.nombreField = value;
                this.RaisePropertyChanged("nombre");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string siglas {
            get {
                return this.siglasField;
            }
            set {
                this.siglasField = value;
                this.RaisePropertyChanged("siglas");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUniversidadesTodas", WrapperNamespace="softplantilla.services", IsWrapped=true)]
    public partial class listarUniversidadesTodasRequest {
        
        public listarUniversidadesTodasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="listarUniversidadesTodasResponse", WrapperNamespace="softplantilla.services", IsWrapped=true)]
    public partial class listarUniversidadesTodasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPlantillaBaseBO.ServicioWS.universidad[] @return;
        
        public listarUniversidadesTodasResponse() {
        }
        
        public listarUniversidadesTodasResponse(SoftPlantillaBaseBO.ServicioWS.universidad[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface UniversidadWSChannel : SoftPlantillaBaseBO.ServicioWS.UniversidadWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class UniversidadWSClient : System.ServiceModel.ClientBase<SoftPlantillaBaseBO.ServicioWS.UniversidadWS>, SoftPlantillaBaseBO.ServicioWS.UniversidadWS {
        
        public UniversidadWSClient() {
        }
        
        public UniversidadWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public UniversidadWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniversidadWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public UniversidadWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPlantillaBaseBO.ServicioWS.listarUniversidadesTodasResponse SoftPlantillaBaseBO.ServicioWS.UniversidadWS.listarUniversidadesTodas(SoftPlantillaBaseBO.ServicioWS.listarUniversidadesTodasRequest request) {
            return base.Channel.listarUniversidadesTodas(request);
        }
        
        public SoftPlantillaBaseBO.ServicioWS.universidad[] listarUniversidadesTodas() {
            SoftPlantillaBaseBO.ServicioWS.listarUniversidadesTodasRequest inValue = new SoftPlantillaBaseBO.ServicioWS.listarUniversidadesTodasRequest();
            SoftPlantillaBaseBO.ServicioWS.listarUniversidadesTodasResponse retVal = ((SoftPlantillaBaseBO.ServicioWS.UniversidadWS)(this)).listarUniversidadesTodas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.listarUniversidadesTodasResponse> SoftPlantillaBaseBO.ServicioWS.UniversidadWS.listarUniversidadesTodasAsync(SoftPlantillaBaseBO.ServicioWS.listarUniversidadesTodasRequest request) {
            return base.Channel.listarUniversidadesTodasAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.listarUniversidadesTodasResponse> listarUniversidadesTodasAsync() {
            SoftPlantillaBaseBO.ServicioWS.listarUniversidadesTodasRequest inValue = new SoftPlantillaBaseBO.ServicioWS.listarUniversidadesTodasRequest();
            return ((SoftPlantillaBaseBO.ServicioWS.UniversidadWS)(this)).listarUniversidadesTodasAsync(inValue);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="softplantilla.services", ConfigurationName="ServicioWS.PostulanteWS")]
    public interface PostulanteWS {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="softplantilla.services/PostulanteWS/insertarPostulanteRequest", ReplyAction="softplantilla.services/PostulanteWS/insertarPostulanteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        SoftPlantillaBaseBO.ServicioWS.insertarPostulanteResponse insertarPostulante(SoftPlantillaBaseBO.ServicioWS.insertarPostulanteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="softplantilla.services/PostulanteWS/insertarPostulanteRequest", ReplyAction="softplantilla.services/PostulanteWS/insertarPostulanteResponse")]
        System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.insertarPostulanteResponse> insertarPostulanteAsync(SoftPlantillaBaseBO.ServicioWS.insertarPostulanteRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="softplantilla.services")]
    public enum modalidad {
        
        /// <remarks/>
        PRESENCIAL,
        
        /// <remarks/>
        VIRTUAL,
        
        /// <remarks/>
        HIBRIDA,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPostulante", WrapperNamespace="softplantilla.services", IsWrapped=true)]
    public partial class insertarPostulanteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPlantillaBaseBO.ServicioWS.universidad arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg2;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg3;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public double arg4;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=5)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool arg5;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=6)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool arg6;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=7)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool arg7;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=8)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public SoftPlantillaBaseBO.ServicioWS.modalidad arg8;
        
        public insertarPostulanteRequest() {
        }
        
        public insertarPostulanteRequest(SoftPlantillaBaseBO.ServicioWS.universidad arg0, string arg1, string arg2, string arg3, double arg4, bool arg5, bool arg6, bool arg7, SoftPlantillaBaseBO.ServicioWS.modalidad arg8) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
            this.arg3 = arg3;
            this.arg4 = arg4;
            this.arg5 = arg5;
            this.arg6 = arg6;
            this.arg7 = arg7;
            this.arg8 = arg8;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="insertarPostulanteResponse", WrapperNamespace="softplantilla.services", IsWrapped=true)]
    public partial class insertarPostulanteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="softplantilla.services", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public insertarPostulanteResponse() {
        }
        
        public insertarPostulanteResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PostulanteWSChannel : SoftPlantillaBaseBO.ServicioWS.PostulanteWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PostulanteWSClient : System.ServiceModel.ClientBase<SoftPlantillaBaseBO.ServicioWS.PostulanteWS>, SoftPlantillaBaseBO.ServicioWS.PostulanteWS {
        
        public PostulanteWSClient() {
        }
        
        public PostulanteWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PostulanteWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostulanteWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PostulanteWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SoftPlantillaBaseBO.ServicioWS.insertarPostulanteResponse SoftPlantillaBaseBO.ServicioWS.PostulanteWS.insertarPostulante(SoftPlantillaBaseBO.ServicioWS.insertarPostulanteRequest request) {
            return base.Channel.insertarPostulante(request);
        }
        
        public int insertarPostulante(SoftPlantillaBaseBO.ServicioWS.universidad arg0, string arg1, string arg2, string arg3, double arg4, bool arg5, bool arg6, bool arg7, SoftPlantillaBaseBO.ServicioWS.modalidad arg8) {
            SoftPlantillaBaseBO.ServicioWS.insertarPostulanteRequest inValue = new SoftPlantillaBaseBO.ServicioWS.insertarPostulanteRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            SoftPlantillaBaseBO.ServicioWS.insertarPostulanteResponse retVal = ((SoftPlantillaBaseBO.ServicioWS.PostulanteWS)(this)).insertarPostulante(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.insertarPostulanteResponse> SoftPlantillaBaseBO.ServicioWS.PostulanteWS.insertarPostulanteAsync(SoftPlantillaBaseBO.ServicioWS.insertarPostulanteRequest request) {
            return base.Channel.insertarPostulanteAsync(request);
        }
        
        public System.Threading.Tasks.Task<SoftPlantillaBaseBO.ServicioWS.insertarPostulanteResponse> insertarPostulanteAsync(SoftPlantillaBaseBO.ServicioWS.universidad arg0, string arg1, string arg2, string arg3, double arg4, bool arg5, bool arg6, bool arg7, SoftPlantillaBaseBO.ServicioWS.modalidad arg8) {
            SoftPlantillaBaseBO.ServicioWS.insertarPostulanteRequest inValue = new SoftPlantillaBaseBO.ServicioWS.insertarPostulanteRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            inValue.arg3 = arg3;
            inValue.arg4 = arg4;
            inValue.arg5 = arg5;
            inValue.arg6 = arg6;
            inValue.arg7 = arg7;
            inValue.arg8 = arg8;
            return ((SoftPlantillaBaseBO.ServicioWS.PostulanteWS)(this)).insertarPostulanteAsync(inValue);
        }
    }
}
