DROP TABLE IF EXISTS plato_ingrediente;
DROP TABLE IF EXISTS ingrediente;
DROP TABLE IF EXISTS plato;
CREATE TABLE plato(
	id_plato INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(150),
    precio DECIMAL(10,2),
    categoria ENUM('ENTRADA','FONDO','POSTRE'),
    foto LONGBLOB,
    activo TINYINT
)ENGINE=InnoDB;
CREATE TABLE ingrediente(
	id_ingrediente INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(150),
    descripcion VARCHAR(500),
    activo TINYINT
)ENGINE=InnoDB;
CREATE TABLE plato_ingrediente(
	id_plato_ingrediente INT PRIMARY KEY AUTO_INCREMENT,
    fid_plato INT,
    fid_ingrediente INT,
    activo TINYINT,
    FOREIGN KEY(fid_plato) REFERENCES plato(id_plato),
    FOREIGN KEY(fid_ingrediente) REFERENCES ingrediente(id_ingrediente)
)ENGINE=InnoDB;
INSERT INTO ingrediente (nombre, descripcion, activo) VALUES 
('AZUCAR', 'ENDULZANTE COMUN USADO EN POSTRES Y BEBIDAS.', 1),
('HARINA', 'INGREDIENTE BASE PARA PANES, PASTELES Y MASAS.', 1),
('SAL', 'CONDIMENTO ESENCIAL PARA SAZONAR COMIDAS.', 1),
('ACEITE DE OLIVA', 'ACEITE USADO PARA COCINAR Y ADEREZAR ENSALADAS.', 1),
('LECHE', 'LIQUIDO LACTEO UTILIZADO EN RECETAS DE POSTRES Y SALSAS.', 1),
('HUEVO', 'INGREDIENTE VERSATIL UTILIZADO EN MASAS Y COMO AGLUTINANTE.', 1),
('MANTEQUILLA', 'GRASA USADA EN REPOSTERIA Y PARA DAR SABOR.', 1),
('QUESO', 'LACTEO USADO COMO RELLENO O COMPLEMENTO EN PLATOS.', 1),
('TOMATE', 'INGREDIENTE BASE PARA SALSAS Y ENSALADAS.', 1),
('CEBOLLA', 'VEGETAL USADO COMO BASE AROMATICA EN GUISOS.', 1),
('AJO', 'CONDIMENTO AROMATICO PARA GUISOS Y ADEREZOS.', 1),
('PEREJIL', 'HIERBA AROMATICA PARA DECORAR Y DAR SABOR.', 1),
('ARROZ', 'CEREAL BASE EN MUCHAS PREPARACIONES.', 1),
('PASTA', 'BASE DE PLATOS ITALIANOS COMO ESPAGUETIS.', 1),
('POLLO', 'PROTEINA ANIMAL VERSATIL PARA MULTIPLES PREPARACIONES.', 1),
('CARNE DE RES', 'PROTEINA ANIMAL UTILIZADA EN GUISOS Y ASADOS.', 1),
('PESCADO', 'INGREDIENTE PRINCIPAL EN RECETAS MARINAS.', 1),
('FRIJOLES', 'LEGUMBRE COMUN EN GUISOS Y SOPAS.', 1),
('PAPA', 'TUBERCULO VERSATIL EN PURE, FRITURAS Y GUISOS.', 1),
('ZANAHORIA', 'VEGETAL DULCE UTILIZADO EN SOPAS Y ENSALADAS.', 1),
('MAIZ', 'GRANO UTILIZADO EN MASAS, GUISOS Y SOPAS.', 1),
('CHOCOLATE', 'INGREDIENTE UTILIZADO EN BEBIDAS Y REPOSTERIA.', 1),
('CANELA', 'ESPECIA AROMATICA USADA EN POSTRES Y BEBIDAS.', 1),
('LIMON', 'FRUTA UTILIZADA EN ADEREZOS Y POSTRES.', 1),
('VAINILLA', 'ESENCIA UTILIZADA PARA PERFUMAR POSTRES Y BEBIDAS.', 1);
DROP PROCEDURE IF EXISTS INSERTAR_PLATO;
DROP PROCEDURE IF EXISTS INSERTAR_PLATO_INGREDIENTE;
DROP PROCEDURE IF EXISTS LISTAR_INGREDIENTES_TODOS;
DELIMITER $
CREATE PROCEDURE INSERTAR_PLATO(
	OUT _id_plato INT,
    IN _nombre VARCHAR(150),
    IN _precio DECIMAL(10,2),
    IN _categoria ENUM('ENTRADA','FONDO','POSTRE'),
    IN _foto LONGBLOB
)
BEGIN
	INSERT INTO plato(nombre,precio,categoria,foto,activo) VALUES(_nombre,_precio,_categoria,_foto,1);
    SET _id_plato = @@last_insert_id;
END$
CREATE PROCEDURE INSERTAR_PLATO_INGREDIENTE(
	OUT _id_plato_ingrediente INT,
    IN _fid_plato INT,
    IN _fid_ingrediente INT
)
BEGIN
	INSERT INTO plato_ingrediente(fid_plato,fid_ingrediente,activo) VALUES(_fid_plato,_fid_ingrediente,1);
    SET _id_plato_ingrediente = @@last_insert_id;
END$
CREATE PROCEDURE LISTAR_INGREDIENTES_TODOS()
BEGIN
	SELECT id_ingrediente, nombre, descripcion FROM ingrediente WHERE activo = 1;
END$